version: '3.8'
services:
  my-bot:
    image: my-bot-image
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-bot-container
    volumes:
      - ./data:/app/data
    command: java -jar /app/my-Bot-jar-with-dependencies.jar