services:
  my-bot:
    image: my-bot-image
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-bot-container
    volumes:
      - ./data:/app/data
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: alex
      SPRING_DATASOURCE_PASSWORD: PiDoTa23
    depends_on:
      - postgres
    command: java -jar /app/my-Bot.jar

  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: alex
      POSTGRES_PASSWORD: PiDoTa23
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  volumes:
    postgres_data:
